# Generated by Django 3.1.5 on 2021-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
