# Generated by Django 3.1.5 on 2021-03-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20210305_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedquery',
            old_name='name',
            new_name='query_name',
        ),
        migrations.AddField(
            model_name='savedquery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='query',
            field=models.JSONField(null=True),
        ),
    ]
