# Generated by Django 3.1.7 on 2021-03-16 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20210305_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='num_stages',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
