# Generated by Django 3.1.7 on 2021-03-17 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_pipeline_num_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('time_window', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)])),
                ('advancement_condition', models.CharField(max_length=100)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipeline')),
            ],
        ),
    ]
