# Generated by Django 3.1.7 on 2021-03-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_step'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Step',
            new_name='Stage',
        ),
    ]
