# Generated by Django 3.1.7 on 2021-03-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_auto_20210317_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='advancement_condition',
            field=models.CharField(choices=[('None', 'None'), ('ER', 'Email Read'), ('FR', 'Form Received')], default='None', max_length=100),
        ),
    ]
