# Generated by Django 3.1.5 on 2021-03-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_auto_20210317_1844'),
        ('pipeline', '0003_auto_20210318_1733'),
    ]

    operations = [
    ]
