# Generated by Django 3.1.5 on 2021-03-31 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210323_1914'),
        ('pipeline', '0007_merge_20210324_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='source',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='pipeline.savedquery'),
        ),
        migrations.AddField(
            model_name='stage',
            name='students',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
