# Generated by Django 3.1.5 on 2021-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_merge_20210324_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
