# Generated by Django 3.1.5 on 2021-04-01 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_pipeline_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='num_stages',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
