# Generated by Django 3.1.5 on 2021-03-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_auto_20210330_1952'),
        ('pipeline', '0008_pipeline_description'),
    ]

    operations = [
    ]
