# Generated by Django 3.1.5 on 2021-04-02 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210323_1914'),
        ('pipeline', '0008_pipeline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.savedquery'),
        ),
        migrations.AddField(
            model_name='stage',
            name='students',
            field=models.ManyToManyField(to='student.Student'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='num_stages',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
