# Generated by Django 3.1.5 on 2021-03-31 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_merge_20210331_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.savedquery'),
        ),
    ]
