# Generated by Django 3.1.5 on 2021-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_auto_20210402_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='source',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source',
            field=models.ManyToManyField(blank=True, null=True, to='pipeline.SavedQuery'),
        ),
    ]
