# Generated by Django 3.1.5 on 2021-04-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_auto_20210405_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='source',
            field=models.ManyToManyField(blank=True, to='pipeline.SavedQuery'),
        ),
    ]
