# Generated by Django 3.1.5 on 2021-04-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_auto_20210405_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='source',
        ),
    ]
