# Generated by Django 3.1.5 on 2021-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_remove_pipeline_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='sources',
            field=models.ManyToManyField(blank=True, to='pipeline.SavedQuery'),
        ),
    ]
