# Generated by Django 3.1.5 on 2021-04-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_auto_20210407_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='sources',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='pipeline.SavedQuery'),
        ),
    ]
