# Generated by Django 3.1.5 on 2021-04-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0017_pipeline_active'),
        ('pipeline', '0017_auto_20210427_1108'),
    ]

    operations = [
    ]
