# Generated by Django 3.1.5 on 2021-04-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_merge_20210428_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='form',
            field=models.CharField(choices=[('None', 'None'), ('DF', 'Demographics Form'), ('RIF', 'Research Interests Form')], default='None', max_length=4),
        ),
    ]
