# Generated by Django 3.1.5 on 2021-05-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_merge_20210429_1047'),
        ('pipeline', '0019_stage_form'),
    ]

    operations = [
    ]
