# Generated by Django 3.1.5 on 2021-05-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0019_stage_subject'),
        ('pipeline', '0020_merge_20210503_1227'),
    ]

    operations = [
    ]
