# Generated by Django 3.1.5 on 2021-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210308_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='student',
            name='research_interests',
            field=models.ManyToManyField(to='student.ResearchInterests'),
        ),
    ]
