# Generated by Django 3.1.5 on 2021-03-21 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210321_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='student',
            name='research_interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='ResearchInterests',
        ),
    ]
