# Generated by Django 3.1.5 on 2021-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210323_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='documents',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
