# Generated by Django 3.1.5 on 2021-03-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210323_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='documents',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
