# Generated by Django 3.1.5 on 2021-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210323_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submitted',
            field=models.BooleanField(default=True),
        ),
    ]
