# Generated by Django 3.1.5 on 2021-04-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submit_demo',
            field=models.BooleanField(default=True),
        ),
    ]
