# Generated by Django 3.1.5 on 2021-04-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_submit_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
