# Generated by Django 3.1.5 on 2021-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='normal_gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
